### ISSUE TITLE
broken example.indexdata.com/templates.html

### ISSUE THREAD

**Issue by dcrossleyau** [indexdata/mkws#2]
Reviewed all of the examples at http://mkws.indexdata.com/
All seems okay, except for two: "templates" and "auto".

The http://example.indexdata.com/templates.html
"specifies how to display brief and full records using Handlebar templates".

However, nothing happens when selecting any.

There are no errors in the console log messages.

**Comment by MikeTaylor** [comment]
Fixed, thanks for spotting this.
