### ISSUE TITLE
broken example.indexdata.com/auto.html

### ISSUE THREAD

**Issue by dcrossleyau** [indexdata/mkws#3]
The http://example.indexdata.com/auto.html
"runs an automatic search on load".

However, it doesn't show any results.

With Safari, there is a server error in the console log messages:
"Failed to load resource: the server responded with a status of 417 (Expectation Failed)".

With Firefox, that error does not seem to be reported.

**Comment by MikeTaylor** [comment]
Fixed, thanks. (The page referred to targets that are no longer enabled in the mkwstest library, for some reason. I changed it to use other targets.
